### ISSUE TITLE
ShortUUIDfield sometimes generates id's that are 21 characters long

### ISSUE THREAD

**Issue by cory-weiner** [benrobster/django-shortuuidfield#4] opened 2014-08-09 21:59 UTC
For example, I had about 3 instances out of 150 where a 21 character ID was generated, such as:
AJojFX5jWX3MfWbjnJLiW

Shouldn't it always be 22 characters?

**Comment by CasherWest** [comment] 2015-02-02 11:29
The python lib shortuuid in the package index ist from 2014-04-18. In the newest version from github the issue is solved.

**Comment by benrobster** [comment] 2015-09-03 21:22
Sorry for the belated response.

If its indeed fixed in the latest version of [shortuuid](https://github.com/stochastic-technologies/shortuuid/) on github, and you can get the folks that maintain that package to update pypi with a new version (or if someone puts an updated fork on pypi under a different name--less than ideal) then that would take care of this. Otherwise, setup.py uses what's on pypi and I can't do a lot.

**Comment by bashu** [comment] 2016-05-05 12:03
latest `shorduuid` release on pypi from 2016-01-11 I suppose this issue can be closed?

**Closed** 2017-12-12 13:51 UTC
